### ISSUE TITLE
Failing if gpg returns non-zero value

### ISSUE THREAD

**Issue by maxanier** [Yubico/gradle-gpg-signing-plugin#3]
The gradle signing plugin seems to allow for making the signing optional (or requiring it only for release builds). I would like to use that option for my project as I don't want to require other developers to have a gpg setup just to build test versions.
However, I am using this cool plugin to be able to use my Yubikey for signing and when no yubikey is available or I cancel the pin dialog the gradle execution stops with the following exception:
```
Caused by: org.gradle.process.internal.ExecException: Process 'command 'gpg2'' finished with non-zero exit value 2
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:389)
        at org.gradle.process.internal.DefaultExecAction.execute(DefaultExecAction.java:36)
        at org.gradle.api.internal.file.DefaultFileOperations.exec(DefaultFileOperations.java:189)
        at org.gradle.api.internal.project.DefaultProject.exec(DefaultProject.java:1087)
        at org.gradle.plugins.signing.signatory.internal.gnupg.GnupgSignatory.sign(GnupgSignatory.java:71)
        at org.gradle.plugins.signing.type.AbstractSignatureType.sign(AbstractSignatureType.java:65)
```

It also seems like this plugin would throw an Exception anyway if the exit code oif the gpg process is non zero https://github.com/Yubico/gradle-gpg-signing-plugin/blob/439520be29c834137c26936b7119dfd6d25ac285/src/main/java/com/yubico/gradle/plugins/signing/gpg/signatory/GpgSignatory.java#L58

I am not really experienced with gradle and don't really know how the gradle signing extension works, but maybe there is a way to not throw an error here if the signing extension is set to optional (not required)

**Comment by maxanier** [comment]
I am not entirely sure if it is an issue of this plugin or the gradle signing process itself

**Comment by maxanier** [comment]
Just noticed that this plugin isn't really required anymore as signing with yubikey and gradle 4.6 works fine without  this plugin (if you use `useGpgCmd()`). The gradle gpg signatory does not support the required option either though.
Closing this
